### ISSUE TITLE
Charge Protection.

### ISSUE THREAD

**Issue by raymondh2** [skiselev/compaq-portable-iii-battery#1]
It seems some revisions of the Compaq Portable III maainboard have a charging circuit. Some being included would be nice to see at a later time.

**Comment by skiselev** [comment]
I am not sure I am familiar with that type of Compaq Portable III
From [this description](http://minuszerodegrees.net/manuals/Compaq/Compaq%20Portable%20III%20-%20CMOS%20battery%20-%20options.htm) it appears that there are two options:
1. External battery, that's exactly what this project is intended to replace. The extra components on the motherboard in this case are a battery switchover circuit, and not a charging circuit
2. Dallas DS1287 RTC module, which includes a built-in battery. In this case, the motherboard will have a few zero ohm links.

If the option that you're referring to is yet another option, I'd appreciate more information on it (e.g., motherboard photos)

**Comment by raymondh2** [comment]
It's the first type. Here the system is on 
![PXL_20220909_201301178](https://user-images.githubusercontent.com/10180760/189435749-9382adc6-f36b-46bb-bfb9-0e0b6b953c37.jpg)
Here the system is off. 
![PXL_20220909_201313398](https://user-images.githubusercontent.com/10180760/189435780-f50a7fb2-92c3-4f4c-a461-6d34d154f747.jpg)

**Comment by skiselev** [comment]
Not sure what I see here. Does it try to charge the battery?
It uses a primary battery, so it shouldn't be charged.
